@ProductsManagement_HostAddress = https://localhost:7162

GET {{ProductsManagement_HostAddress}}/weatherforecast/
Accept: application/json

### Get all products

GET {{ProductsManagement_HostAddress}}/api/products
Accept: application/json

### Get product by id

@id=2
GET {{ProductsManagement_HostAddress}}/api/products/{{id}}
Accept: application/json

### Update a product
@id=2
PUT {{ProductsManagement_HostAddress}}/api/products/{{id}}
Content-Type: application/json
Accept: application/json

{
  "id": 2,
  "name": "Smartphone 2026",
  "price": 199.99,
  "description": "Latest model smartphone"
}

### Delete a product
@id=2
DELETE {{ProductsManagement_HostAddress}}/api/products/{{id}}
Accept: application/json

###

POST {{ProductsManagement_HostAddress}}/api/products
Content-Type: application/json

{
  //Product
}

###
