using Scalar.AspNetCore;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();
builder.Services.AddSwaggerGen(); //Registers Swagger/OpenAPI generation services with DI.

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.MapScalarApiReference(); // enables use of Scalar API reference UI in development environment

    // Use swagger and configure Swagger UI
    app.UseSwagger(); // Adds middleware that serves the OpenAPI JSON (the document generated by AddSwaggerGen); Enable middleware to serve generated Swagger as a JSON endpoint; Exposes /swagger/v1/swagger.json
    app.UseSwaggerUI(); // Adds middleware that serves the interactive Swagger UI at a route (default /swagger); Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.),
                        // specifying the Swagger JSON endpoint.
    app.UseSwaggerUI(c =>
    {
        // configure Swagger UI settings here for endpoint definition
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "ProductsManagement v1"); //  Load the v1 document and label it
        c.RoutePrefix = string.Empty; // Set Swagger UI at the app's root
    });
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
