using ProductsManagement.Data;
using ProductsManagement.DTOs;
using ProductsManagement.Models;

namespace ProductsManagement.Services
{
    public class ProductService : IProductService
    {
        private readonly AppDbContext context;

        public ProductService(AppDbContext appDbContext) 
        { 
            context = appDbContext; // inject the appDbContext dependency
        }

        public ProductResponse AddProduct(ProductRequest productRequest)
        {
            var product = new Product
            {
                Id = 0, // Id will be generated by the database
                Name = productRequest.Name,
                Price = productRequest.Price,
                Description = productRequest.Description
            };
            var newProduct = context.Products.Add(product); // add the new product to the database
            context.SaveChanges(); // save changes to the database

            var response = new ProductResponse
            {
                Id = newProduct.Entity.Id,
                Name = newProduct.Entity.Name,
                Price = newProduct.Entity.Price,
                Description = newProduct.Entity.Description
            };
            return response; // return the added product entity
        }

        public void DeleteProduct(int id)
        {
            var product = context.Products.Find(id);
            if (product != null)
            {
                context.Products.Remove(product);
                context.SaveChanges();
            }
        }

        public IEnumerable<ProductResponse> GetAllProducts()
        {
            var products = context.Products.ToList(); // retrieve all products from the database
            var response = products.Select(p => new ProductResponse
            {
                Id = p.Id,
                Name = p.Name,
                Price = p.Price,
                Description = p.Description
            });
            return response;
        }

        public ProductResponse? GetProductById(int id)
        {
            var product = context.Products.Find(id); // find the product by id
            if (product == null)
            {
                return null;
            }
            return new ProductResponse
            {
                Id = product.Id,
                Name = product.Name,
                Price = product.Price,
                Description = product.Description
            };
        }

        public void UpdateProduct(int id, Product product)
        {
            var existingProduct = context.Products.Find(id);
            if (existingProduct != null)
            {
                existingProduct.Name = product.Name;
                existingProduct.Price = product.Price;
                existingProduct.Description = product.Description;
                context.SaveChanges();
            }
        }
    }
}
