using ProductsManagement.Data;
using ProductsManagement.DTOs;
using ProductsManagement.Models;

namespace ProductsManagement.Services
{
    public class ProductService : IProductService
    {
        private readonly AppDbContext context;

        public ProductService(AppDbContext appDbContext) 
        { 
            context = appDbContext; // inject the appDbContext dependency
        }

        public Product AddProduct(ProductRequest productRequest)
        {
            var product = new Product
            {
                Id = 0, // Id will be generated by the database
                Name = productRequest.Name,
                Price = productRequest.Price,
                Description = productRequest.Description
            };
            var newProduct = context.Products.Add(product); // add the new product to the database
            context.SaveChanges(); // save changes to the database
            return newProduct.Entity; // return the added product entity
        }

        public void DeleteProduct(int id)
        {
            var product = context.Products.Find(id);
            if (product != null)
            {
                context.Products.Remove(product);
                context.SaveChanges();
            }
        }

        public IEnumerable<Product> GetAllProducts()
        {
            var products = context.Products.ToList(); // retrieve all products from the database
            return products;
        }

        public Product? GetProductById(int id)
        {
            var product = context.Products.Find(id); // find the product by id
            return product;
        }

        public void UpdateProduct(int id, Product product)
        {
            var existingProduct = context.Products.Find(id);
            if (existingProduct != null)
            {
                existingProduct.Name = product.Name;
                existingProduct.Price = product.Price;
                existingProduct.Description = product.Description;
                context.SaveChanges();
            }
        }
    }
}
